[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.install-user]
script = "echo '[ERROR!] [Only linux supports this feature at the moment]'"
linux_alias = "linux_user_install"
windows_alias = "platform_not_supported"

[tasks.install]
alias = "unix_install"
windows_alias = "platform_not_supported"

[tasks.unix_install]
script = "sudo cp target/release/fetch /usr/local/bin/fetch"
dependencies = ["build"]

[tasks.linux_user_install]
script = "cp target/release/fetch ~/.local/bin/fetch"
dependencies = ["build"]

[tasks.platform_not_supported]
command = "echo"
args = ["[This platform is not supported at the moment]"]
